databases:
  - name: peluqueria_db
    databaseName: peluqueria_anita
    user: peluqueria_user
    plan: free

services:
  - type: web
    name: peluqueria-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_NAME
        value: "Peluquería Anita"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: peluqueria_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: peluqueria_db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: peluqueria_db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: peluqueria_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: peluqueria_db
          property: password
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
